// @ts-nocheck
import React from 'react';
import HelpTip from '../../HelpTip';
import { IMAGE_MODELS, SCRIPT_MODEL_OPTIONS } from '../../../config';
import { ASPECT_RATIO_OPTIONS, getAspectRatioClass, getAspectRatioDescription } from '../../../utils/aspectRatio';
import { handleHorizontalWheel, scrollContainerBy } from '../../../utils/horizontalScroll';
import { getTopicSuggestion } from '../../../services/storyRecommendationService';
import { buildWorkflowPromptPack, resolveWorkflowPromptTemplates } from '../../../services/workflowPromptBuilder';
import { WorkflowPromptTemplate } from '../../../types';
import { CONTENT_TYPE_CARDS, FIELD_OPTIONS_BY_TYPE, STEP_META } from '../constants';
import {
  AccordionSection,
  ArrowButton,
  GuidedActionButton,
  LoadingSlide,
  StepChip,
  SummaryChip,
} from '../ui';

export default function MainStepView({ vm }: { vm: any }) {
  const {
    routeStep,
    completion,
    notice,
    openStage,
    activeStage,
    toggleStage,
    stageStatus,
    step1Summary,
    step2Summary,
    step3Summary,
    step4Summary,
    step3GuideItems,
    contentType,
    hasSelectedContentType,
    hasSelectedAspectRatio,
    aspectRatio,
    setHasSelectedContentType,
    setContentType,
    setTopic,
    setStoryScript,
    setGenre,
    setMood,
    setEndingTone,
    setSetting,
    setProtagonist,
    setConflict,
    setExtractedCharacters,
    setStyleImages,
    setSelectedCharacterIds,
    setSelectedStyleImageId,
    setHasSelectedAspectRatio,
    setAspectRatio,
    topic,
    isRefreshingTopic,
    refreshTopicRecommendation,
    topicRecommendations,
    fieldConfigs,
    refreshField,
    loadingFields,
    selectedPromptTemplate,
    selectedPromptTemplateId,
    syncedPromptTemplates,
    focusPromptTemplate,
    openPromptEditor,
    deleteCustomPromptTemplate,
    addCustomPromptTemplate,
    handleGenerateScriptClick,
    createDraftFromSelections,
    isGeneratingScript,
    customScriptDurationMinutes,
    customScriptSpeechStyle,
    customScriptLanguage,
    customScriptReferenceText,
    scriptReferenceSuggestions,
    setCustomScriptDurationMinutes,
    setCustomScriptSpeechStyle,
    setCustomScriptLanguage,
    setCustomScriptReferenceText,
    applyScriptReferenceSuggestion,
    refreshScriptReferenceSuggestions,
    selectedScriptGenerationModel,
    customScriptModelOptions,
    setSelectedScriptGenerationModel,
    ensureProjectPromptTemplate,
    setPromptPreviewDraft,
    setPromptPreviewId,
    storyScript,
    sceneCount,
    selectedCharacters,
    selectedStyle,
    connectionSummary,
    selectedScriptModel,
    selectedImageModel,
    onOpenApiModal,
    hydrateCharactersForScript,
    isExtracting,
    characterUploadInputRef,
    handleUpload,
    newCharacterName,
    setNewCharacterName,
    newCharacterPrompt,
    setNewCharacterPrompt,
    createNewCharacterByPrompt,
    extractedCharacters,
    characterStripRef,
    characterCarouselIndices,
    setCharacterCarouselIndices,
    characterLoadingProgress,
    chooseCharacterImage,
    toggleCharacterSelection,
    createCharacterVariants,
    expandedCharacterEditorId,
    setExpandedCharacterEditorId,
    updateCharacterName,
    updateCharacterPrompt,
    updateCharacterRole,
    updateCharacterRoleLabel,
    removeCharacter,
    selectedCharacterIds,
    ensureStyleRecommendations,
    newStyleName,
    setNewStyleName,
    newStylePrompt,
    setNewStylePrompt,
    createNewStyleByPrompt,
    styleGroups,
    styleStripRef,
    styleCarouselIndices,
    setStyleCarouselIndices,
    styleLoadingProgress,
    createStyleVariants,
    expandedStyleEditorId,
    setExpandedStyleEditorId,
    updateStylePrompt,
    stepCompleted,
    handleOpenSceneStudioClick,
    visibleStepIds,
    setCharacterLoadingProgress,
    setStyleLoadingProgress,
    autoRecommendSignatureRef,
    setPromptTemplates,
    setSelectedPromptTemplateId,
    setPromptDetailId,
    setNotice,
    completeStage,
    openExampleGuide,
    normalizedScript,
    setShowPromptPack,
    showPromptPack,
    onUpdateRouting,
    textModelReady,
    step3PanelMode,
    setStep3PanelMode,
    activePromptSlide,
    selectedPromptIndex,
    generateScriptByPrompt,
    promptDetailTemplate,
    promptPack,
    onOpenSettings,
    studioState,
    imageModelReady,
    openStageWithIntent,
    step4CharacterStripRef,
    styleUploadInputRef,
    selectedStyleImageId,
  } = vm;


  return (
    <>
      <div className="mt-6 space-y-6">

      </div>
    </>
  );
}

