import type { ProductItem } from "@/lib/i18n/types";

import { ACCOUNT_GUIDE_URL, serviceKeyCredential } from "../shared";

const SERVICE_KEY_SAMPLE = "YOUR_DATA_GO_KR_SERVICE_KEY";

const product: ProductItem = {
  slug: "api-15136560",
  collectorKey: "condition-paging",
  title: "건축HUB 주택 인허가 조회",
  summary: "시도와 시군구를 선택해 건축HUB 주택 인허가 데이터를 조회하고 내려받을 수 있습니다.",
  description:
    "공공데이터포털 Data ID 15136560 API를 바탕으로 건축HUB 주택 인허가 기본개요와 총괄개요 데이터를 통합 조회하는 분석 페이지입니다.",
  stack: ["Node.js", "TypeScript", "REST API", "JSON", "XLSX"],
  status: "분석 가능",
  priceLabel: "Data ID 15136560",
  priceValue: 390000,
  delivery: "조건 입력 후 바로 조회",
  audience: "지역별 인허가 흐름과 건축 규모를 빠르게 확인해야 하는 사용자",
  features: [
    "시도와 시군구만 선택하면 법정동 전체를 자동으로 조회합니다.",
    "승강기 조건과 지역 필터를 함께 적용할 수 있습니다.",
    "인허가일자와 착공일자를 기준으로 결과를 필터링할 수 있습니다.",
    "결과는 지역별 엑셀, 전체 엑셀, 필터 엑셀로 저장할 수 있습니다.",
    "인증키가 없으면 실제 데이터 미리보기 5건만 표시됩니다.",
  ],
  portalDataId: "15136560",
  apiDocUrl: "https://www.data.go.kr/data/15136560/openapi.do",
  accountGuideUrl: ACCOUNT_GUIDE_URL,
  collectFocus: "건축HUB 주택 인허가 기본개요 및 총괄개요 데이터",
  inputFields: [
    {
      key: "serviceKey",
      label: "인증키(serviceKey)",
      example: "",
      required: true,
    },
    {
      key: "startDate",
      label: "인허가일자 시작(YYYYMMDD)",
      example: "",
      required: false,
    },
    {
      key: "endDate",
      label: "인허가일자 종료(YYYYMMDD)",
      example: "",
      required: false,
    },
    {
      key: "constructionStartDate",
      label: "착공일자 시작(YYYYMMDD)",
      example: "",
      required: false,
    },
    {
      key: "constructionEndDate",
      label: "착공일자 종료(YYYYMMDD)",
      example: "",
      required: false,
    },
  ],
  sampleRequest:
    "?serviceKey=YOUR_DATA_GO_KR_SERVICE_KEY&sigunguCd=11680&bjdongCd=10300&startDate=20260306&endDate=20260313&_type=json&pageNo=1&numOfRows=100",
  apiCredential: serviceKeyCredential("15136560"),
  apiRuntime: {
    endpoint: "https://apis.data.go.kr/1613000/HsPmsHubService/getHpDongOulnInfo",
    responsePathHint: "response.body.items.item",
    forcedQuery: {
      pageNo: "1",
      numOfRows: "100",
      _type: "json",
    },
  },
  workbench: {
    columns: [
      { key: "permitType", label: "인허가구분" },
      { key: "permitNo", label: "인허가번호" },
      { key: "permitReportDate", label: "인허가신고일" },
      { key: "agency", label: "지역" },
      { key: "buildType", label: "건축물구분" },
      { key: "siteLocation", label: "대지위치" },
      { key: "landCategory", label: "지목" },
      { key: "siteArea", label: "대지면적" },
      { key: "buildingArea1", label: "건축면적" },
      { key: "buildingCoverageRatio", label: "건폐율(%)" },
      { key: "totalFloorArea1", label: "연면적" },
      { key: "floorAreaForRatio1", label: "용적률산정면적" },
      { key: "floorAreaRatio", label: "용적률(%)" },
      { key: "buildingName", label: "건축물명" },
      { key: "mainUsage1", label: "주용도" },
      { key: "mainBuildingCount", label: "주건축물수" },
      { key: "annexBuildingCount", label: "부속건축물수" },
      { key: "parkingAutoIndoor", label: "주차대수 자동차 실내" },
      { key: "parkingAutoOutdoor", label: "주차대수 자동차 실외" },
      { key: "parkingAutoNearby", label: "주차대수 자동차 부설외" },
      { key: "parkingMachineIndoor", label: "주차대수 기계식 실내" },
      { key: "parkingMachineOutdoor", label: "주차대수 기계식 실외" },
      { key: "parkingMachineNearby", label: "주차대수 기계식 부설외" },
      { key: "parkingExempt", label: "주차대수 면제" },
      { key: "constructionType", label: "착공구분" },
      { key: "constructionPlannedDate", label: "착공예정일" },
      { key: "constructionActualDate", label: "실착공일" },
      { key: "useApprovalType", label: "사용승인구분" },
      { key: "useApprovalDate", label: "사용승인일" },
      { key: "dongName", label: "동명칭" },
      { key: "mainUsage2", label: "주용도(상세)" },
      { key: "etcUsage", label: "기타용도" },
      { key: "householdCount", label: "세대수" },
      { key: "hoCount", label: "호수" },
      { key: "familyCount", label: "가구수" },
      { key: "structureMain", label: "주구조" },
      { key: "structureEtc", label: "기타구조" },
      { key: "roofStructure", label: "지붕구조" },
      { key: "buildingArea2", label: "건축면적(상세)" },
      { key: "totalFloorArea2", label: "연면적(상세)" },
      { key: "floorAreaForRatio2", label: "용적률산정면적(상세)" },
      { key: "undergroundFloors", label: "지하층수" },
      { key: "groundFloors", label: "지상층수" },
      { key: "heightM", label: "높이(m)" },
      { key: "passengerElevators", label: "승용승강기수" },
      { key: "emergencyElevators", label: "비상용승강기수" },
    ],
    rows: [],
  },
};

export default product;
