export const CHUNK_SIZE = 50;

export const HIDDEN_META_KEYS = new Set([
  "resultCode",
  "resultMsg",
  "numOfRows",
  "pageNo",
  "totalCount",
]);

export const REGION_OPTIONS = [
  { code: "6110000", name: "서울특별시" },
  { code: "6260000", name: "부산광역시" },
  { code: "6270000", name: "대구광역시" },
  { code: "6280000", name: "인천광역시" },
  { code: "6290000", name: "광주광역시" },
  { code: "6300000", name: "대전광역시" },
  { code: "6310000", name: "울산광역시" },
  { code: "5690000", name: "세종특별자치시" },
  { code: "6410000", name: "경기도" },
  { code: "6530000", name: "강원특별자치도" },
  { code: "6430000", name: "충청북도" },
  { code: "6440000", name: "충청남도" },
  { code: "6540000", name: "전북특별자치도" },
  { code: "6460000", name: "전라남도" },
  { code: "6470000", name: "경상북도" },
  { code: "6480000", name: "경상남도" },
  { code: "6500000", name: "제주특별자치도" },
] as const;

export const REGION_NAME_MAP = Object.fromEntries(
  REGION_OPTIONS.map((item) => [item.code, item.name]),
);

export const WORKNATIONAL_MAP: Record<string, string> = {
  "101": "중국",
  "102": "몽골",
  "103": "스리랑카",
  "104": "우즈베키스탄",
  "105": "인도네시아",
  "106": "태국",
  "108": "베트남",
  "109": "캄보디아",
  "110": "파키스탄",
  "111": "네팔",
  "112": "미얀마",
  "113": "방글라데시",
  "125": "중앙아시아",
  "134": "동남아시아",
  "138": "남아시아",
  "145": "동아시아",
  "148": "네팔",
  "153": "인도네시아",
  "155": "서유럽",
  "156": "중국",
  "181": "서아시아",
};

export const COLUMN_LABEL_KR: Record<string, string> = {
  worknational: "근무국가",
  localCompanyName: "현지업체명",
  recruitNum: "채용인원",
  plcNm: "교육장명",
  orgHanNm: "기관명",
  telNo: "전화번호",
  faxNo: "팩스번호",
  addr: "주소",
  etcAd: "기타안내",
  regTime: "등록시간",
  receiptNo: "접수번호",
  nationalName: "국적",
  worktypeMain1Name: "희망직종(대)",
  worktypeSub1Name: "희망직종(중)",
  worktypeSub2Name: "희망직종(소)",
  worktypeSub3Name: "희망직종(세부)",
  careerMonth: "경력(개월)",
  koreanAbility: "한국어능력",
  OPN_ATMY_GRP_CD: "개방자치단체",
  MNG_NO: "관리번호",
  GSRM_CNT: "객실수",
  BLDG_USG_NM: "건물용도명",
  ARCH_TFA: "건축연면적",
  SVNR_KND: "기념품종류",
  DAT_UPDT_SE: "데이터변경구분",
  DAT_UPDT_PNT: "데이터변경시점",
  ROAD_NM_ZIP: "도로명우편번호",
  ROAD_NM_ADDR: "도로명주소",
  STAGE_AREA: "무대면적",
  CULTR_BZMN_SE_NM: "문화사업자구분",
  CULTR_SPTS_TPBIZ_NM: "문화체육업종명",
  INSRNC_INST_NM: "보험기관명",
  INSRNC_BGNG_YMD: "보험시작일",
  INSRNC_END_YMD: "보험종료일",
  BPLC_NM: "사업장명",
  DTL_SALS_STTS_NM: "상세영업상태명",
  DTL_SALS_STTS_CD: "상세영업상태코드",
  VSL_SPEC: "선박제원",
  VSL_SCNT_CNT: "선실수",
  VSL_TOTAL_TON: "총톤수",
  FCLT_SCL: "시설규모",
  FCAR: "시설차량",
  ENG_CONM_NM: "영문상호명",
  ENG_CONM_ADDR: "영문주소",
  SALS_STTS_NM: "영업상태명",
  SALS_STTS_CD: "영업상태코드",
  LCPMT_YMD: "인허가일자",
  LCPMT_RTRCN_YMD: "인허가취소일자",
  CPTL: "자본금",
  TELNO: "전화번호",
  FBCTN_HNDL_ITEM_CN: "취급품목",
  SEAT_CNT: "좌석수",
  CRD_INFO_X: "좌표X",
  CRD_INFO_Y: "좌표Y",
  SURRND_ENVRNMNT_NM: "주변환경명",
  LOTNO_ADDR: "지번주소",
  GRND_NOFL: "지상층수",
  RGN_SE_NM: "권역구분명",
  UDGD_NOFL: "지하층수",
  TOTAL_NOFL: "총층수",
  CLSBIZ_YMD: "폐업일자",
  CFRM_PER_CNCR_ACTC_PERNE: "확인자성명",
  TCBIZ_BGNG_YMD: "영업시작일",
  TCBIZ_END_YMD: "영업종료일",
  LCTN_ZIP: "소재지우편번호",
  LAST_MDFCN_PNT: "최종수정시점",
};